# Generated by Django 4.1.3 on 2022-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('MobileNumber', models.CharField(default='', max_length=100)),
                ('EmailID', models.CharField(default='', max_length=100)),
                ('DrName', models.CharField(default='', max_length=100)),
                ('Treatment', models.CharField(default='', max_length=100)),
                ('LatestPathelogyReport', models.CharField(default='', max_length=100)),
                ('ProblemSinceMonths', models.CharField(default='', max_length=100)),
                ('Diseases', models.CharField(default='', max_length=100)),
                ('Symptoms', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
